Завдання 8.3
rom-nov/rtacademy-homework pull request #11
Opened 2022-07-08 18:32 UTC by rom-nov

2022-07-13 18:29 UTC, roman-rtacademy commented on block-08/08-3/8.3.sql
> +    unique (email)
Тобто можна вставити два записи `roman@rtacademy.net` та `rOmAn@rTaCaDeMy.net`  ?

2022-07-14 19:30 UTC, rom-nov commented on block-08/08-3/8.3.sql
> +    unique (email)
В мене не записує у базу з такими значеннями поля email: "novikov@gmail.com" та "noVIKov@gmail.com", я так розумію, що обмеження unique працює. Але є можливість записати, наприклад такий email: "nov1kov@gmail.com". Технічно рядки:"novikov@gmail.com" та "nov1kov@gmail.com" - різні, бо у першому випадку я використав "i", а у другому "1", чи я не правий?
SQL має інструмент для обмеження подібних випадків?

2022-07-21 08:14 UTC, roman-rtacademy commented on block-08/08-3/8.3.sql
> +    unique (email)
Так, наприклад lower(email) або upper(email)

2022-07-21 08:23 UTC, roman-rtacademy requested changes
Див. коментарі

2022-08-07 09:12 UTC, closed without merging