Завдання 8.4
rom-nov/rtacademy-homework pull request #22
Opened 2022-08-07 19:39 UTC by rom-nov

Щось важко з адресою доставки... Здається мені, що має бути так:
1. Є таблиця областей.
2. У області є райони. Одній обасті відповідає декілька районів (one-to-many).
3. У районі є міста. Одному району відповідає декілька міст (one-to-many).
4. У місті є вулиці. Одному місту відповідає декілька вулиць (one-to-many).
5. У вулиці є будинки. Одній вулиці відповідає декілька будинків (one-to-many).
6. У будинка є квартири. Одному будинку відповідає декілька квартие (one-to-many). Але мені здається, що квартира не потібна і вістачить номера будинку, бо зазвичай доставляють до будинку.
А ось далі в мене проблема, як тепер цю піраміду адреси коректно пов'язати з замовленням?
І стосовно знижки, мені здається, що краще зробити знижку на товар, бо в магазина можуть бути акції на товари + персональну знижку покупця. Додавши одну до іншої отримаємо знижку на замовлення.

2022-08-14 04:49 UTC, roman-rtacademy reviewed
sale (знижка) має бути на замовлення. Бо сьогодні це 10%, а завтра 50%. І якщо дивитись на дані через який час, то не можна буде сказати яка була знижка на замовлення рік тому.

2022-08-14 04:51 UTC, roman-rtacademy reviewed
Не розумію що буде у `orders.address_id`, ти ж не отримаєш адресу доставки. Якось дуже складно.

2022-08-14 04:51 UTC, roman-rtacademy requested changes
Чекаю оновлення

2022-08-28 15:26 UTC, rom-nov commented
> sale (знижка) має бути на замовлення. Бо сьогодні це 10%, а завтра 50%. І якщо дивитись на дані через який час, то не можна буде сказати яка була знижка на замовлення рік тому.
Тут я не зовсім розумію чому я не можу зробити запит до order та витягнути sale на товар та додати до нього sale клієнта і таким чином отримати сумарну знижку на товар у замовленні...
Так, якщо одне замовлення буде складатися з 10 товарів, то треба буде обробити кожен окремо але це не треба робити "вручну" можна прописати код для цього, чи це я теж намудрував? :)

> Не розумію що буде у `orders.address_id`, ти ж не отримаєш адресу доставки. Якось дуже складно.
Я згоден, що це складно виходить. Я ломав голову, як таку залежність поєднати у цілісну сутність та нічого не вигадав :(
Можливо я дісно все ускладнюю але мені здається що всі пункти у адресі: "Область", "Район", "Місто", "Вулиця" і т.д. мають залежати один від одного, бо назва вулиці може змінитися, або назва міста і тоді замінивши цю назву у одній таблиці, вся решта записів буде мати актуальну інформацію, чи можливо я не правий?
Я розглядав варіант, взагалі зробити адресу тупо рядком, яку користувач має заповнити але мені здається, що буде втрачена актуальність інформації, якщо назви міст або вулиць будуть змінені.

Можливо я дійсно все ускладнюю та намагаюсь зробити дуже гібким, а воно виходить таке гібке, що аж м'ягке :)

2022-08-28 16:35 UTC, rom-nov commented
Додав 2 варіанти реалізації.
Перший варіант може працювати при умові, якщо всі поля адреси будуть обов'язковими для заповнення, а інакше може не бути "Району", "Області", "Квартири" і тоді ці поля будуть мати null, тобто значення, що повторюється у одному запису, а це не добре.
Другий варіант - це максимально просте рішення, користувачь зможе записати будь яку інформацію стосовно адреси доставки але так само він може заповнити якусь фігню і тому мені здається, що це "так собі" рішення.

Підсумовуючи усе вище зазначене, краще мені не робити побудову архітектури БД :)

2022-09-03 17:40 UTC, roman-rtacademy approved these changes

2022-09-03 17:40 UTC, merged