Завдання 11.7
rom-nov/rtacademy-homework pull request #25
Opened 2022-08-16 09:48 UTC by rom-nov

Було боляче але щось таки вийшло :)

2022-09-03 17:42 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +            function safe_work( $message )
Типізація

2022-09-03 17:42 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +            function check_uploaded_file( $name, $max_size = 10485760 )
Типізація

2022-09-03 17:43 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +                switch( true )
Цікаво, але краще зробити через набір `if( !someFunc() ) {...}`.

А ще краще - через chain методами класу

2022-09-03 17:44 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +                if( empty( $file_name ) )
Тобто це ж 
```
return empty( $file_name );
```
?

2022-09-03 17:45 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +            function is_empty( $file_name )
Типізація. Що повертає коли умова false?

2022-09-03 17:46 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +            $img_origin = creat_img( 'img' );
А чому це все не в якойсь фукнції типу main() ?

2022-09-03 17:47 UTC, roman-rtacademy requested changes
Див. коментарі

2022-09-12 18:52 UTC, rom-nov commented
Додав типізацію. Вирішив "пощюпати" об'єкти, спробував зробити ланцюг методів об'єкта.
Здається кроп-метод GDImages на великих файлах погано працює, чи то я щось не так роблю. Потім покажу.

2022-09-19 04:47 UTC, roman-rtacademy commented on block-11/11-07/ControlLoadFile.php
> +	private function is_empty() : object
Щоб типізувати, можна писати заміть `: object` - `: self` або назву класу. 
Але якщо будеш робити extends, тоді краще імʼя інтерфейсу, який треба буде звісно також створити.

2022-09-19 04:50 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +        require 'ControlLoadFile.php';
Можеш спробувати автозавантаження через spl_autoload_register(), але це опціонально

2022-09-19 04:51 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +                $img -> destroy();
Так це можна перенести у 36 ряд, бо воно не видалить сам екземпляр класу для твого методу `full_path()`

2022-09-19 04:51 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +        if( empty( $_FILES ) & empty( $_POST ) )
`&` ?

2022-09-22 13:00 UTC, roman-rtacademy commented on block-11/11-07/index.php
> +        function main( string $img_file ) : void
Опціонально. Спробуй розділяли логіку та view.

2022-09-22 13:00 UTC, roman-rtacademy commented on block-11/11-07/ImageModifyAbstract.php
> +			throw new Exception( 'Ширина та висота зображення має бути більше' . $size . 'px.' );
Після "більше" треба поставити пробіл

2022-09-22 13:01 UTC, roman-rtacademy commented on block-11/11-07/ImageModifyAbstract.php
> +	public function save_file( int|string $name, string $type = '.jpg', string $path = './', string $dir = 'data/' ) : self
А чому `int|string $name`? Може просто "string"?

2022-09-22 13:02 UTC, roman-rtacademy commented on block-11/11-07/ImageModifyAbstract.php
> +<?php
declare( strict_types = 1);

2022-09-27 18:19 UTC, rom-nov commented
Дуже сподобалась твоя реалізація, я у захваті від технічного класу Kernel, що містить всі налаштування в одному місті і передає їх у методи об'єктів, мега зручно. Вирішив теж переробити свій код, зробивши теж технічний клас і винести у нього логіку та налаштування. Бо спочатку я всі константи розкидав по інтерфейсах, що виявилось не дуже зручно, бо мусиш переходити по них щоб щось змінити, а з часом вже і не пригадаєш у якому інтерфейсі, які константи і налаштування. Додатково, теж все виніс у окрему теку "lib" + попрацював з namespace. Круто, я в захваті, php починає подобатися :)

2023-03-11 20:26 UTC, merged