Завдання 11.5
rom-nov/rtacademy-homework pull request #26
Opened 2022-08-24 20:17 UTC by rom-nov

Я не знаю, як нормальні люди створюють html файли та сторінки використовуючи php, тому представляю вашій увазі створення html файлу "курця", а не звичайної людини :)

2022-09-03 17:50 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +	header( 'Location: http://127.0.0.1/block-11/11-05/cities.html' );
Виходить що ти вже ставиш заголовок redirect'у, навіть якщо з якихось причин не спрацю скрипт і тобі треба буде показати помилку? (наприклад немає дозволу на читання або запис файлу, закінчилось місце на диску чи просто відсутній вхідний файл).

2022-09-03 17:50 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +            </tr>');
Краще тоді писати так, щоб не було зайвих пробілів у вихідному HTML. Наприклад розбиваючи на `'...' . '...'` через Enter

2022-09-03 17:51 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +		$array[ 'city' ] = trim( $array_str[ 0 ] );
А де ти визначаєш змінну $array?

2022-09-03 17:55 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +		if( ( $resource = fopen( $path, 'r' ) ) === false )
Тобто `if( !$resource = fopen( $path, 'r' ) ) { ... }` ?

2022-09-03 17:55 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +		if( ( $resource = fopen( $path, 'r' ) ) === false )
А якщо файлу не буде, то спрацює ця перевірка належним чином?

2022-09-03 17:56 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +    function csv_in_array( $csv ) : array
Типізація

2022-09-03 17:57 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +		$array[ 'population' ] = ( int )$array_str[ 4 ];
А якщо немає такого індексу?

2022-09-03 17:57 UTC, roman-rtacademy commented on block-11/11-05/index.php
> +    $path = './cities.csv';
Краще це все тримати також у функції

2022-09-03 17:57 UTC, roman-rtacademy commented on block-11/11-05/style.css
> +    padding: 01em;
`01em;` ?

2022-09-03 17:58 UTC, roman-rtacademy requested changes
Див. коментарі

2022-09-04 18:59 UTC, rom-nov commented on block-11/11-05/index.php
> +		if( ( $resource = fopen( $path, 'r' ) ) === false )
Перед викликом is_open() виконується is_exists() але якщо виникло таке питання, то мабуть слід переробити.

2022-09-04 18:59 UTC, rom-nov commented on block-11/11-05/index.php
> +		$array[ 'city' ] = trim( $array_str[ 0 ] );
переробив цей жах

2022-09-04 19:01 UTC, rom-nov commented on block-11/11-05/index.php
> +		$array[ 'population' ] = ( int )$array_str[ 4 ];
перед викликом convert_type() у csv_in_array() виконую перевірку на кількість елементів

2022-09-04 19:03 UTC, rom-nov commented on block-11/11-05/index.php
> +    function csv_in_array( $csv ) : array
не розумію як задати "resource" у якості типу, що повертає функція або як задати "resource" у якості типу для параметра функції

2022-09-04 19:03 UTC, rom-nov commented on block-11/11-05/index.php
> +    $path = './cities.csv';
переробив

2022-09-04 19:08 UTC, rom-nov commented on block-11/11-05/index.php
> +            </tr>');
мені PhpStorm підказує, що краще це зробити через "const". Я спробував - працює.
Ось, що знайшов у доках php:
Константа может быть определена с помощью ключевого слова const или с помощью функции define(). В то время как define() позволяет задать константу через выражение, конструкция const ограничена как описано в следующем параграфе.
При использовании ключевого слова const допускаются только скалярные выражения (bool, int, float и string) и константы array, содержащие только скалярные выражения.

2022-09-04 19:10 UTC, rom-nov commented on block-11/11-05/index.php
> +	header( 'Location: http://127.0.0.1/block-11/11-05/cities.html' );
дійсно, дивно зробив... я пам'ятаю, що "header" має бути до виводу будь чого, тому довго не розмірковуючи лупанув його з самого початку.
переробив.

2022-09-04 19:10 UTC, rom-nov commented on block-11/11-05/style.css
> +    padding: 01em;
боже який позор :)

2022-09-18 08:55 UTC, roman-rtacademy approved these changes

2022-09-18 08:55 UTC, merged